[[command]]
regex = "^;.*"
default_decorator = ["BlackFgBright"]

[[command]]
regex = "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$"
default_decorator = ["GreenFgBright"]

[[command]]
regex = "^[^;](\\S+\\.){1,}\\S+"
default_decorator = ["BlueFgBright"]

[[command]]
regex = "(?<=CNAME\\s+).*(?=\\.)"
default_decorator = ["MagentaFgBright"]
