[[command]]
regex = "Server|Address|Non-authoritative\\s+answer|Name|canonical\\s+name"
default_decorator = ["Underlined"]

[[command]]
regex = "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|([a-z0-9]+\\:(\\:\\S+)?){2,}"
default_decorator = ["GreenFgBright"]

[[command]]
regex = "(?<=#)\\d+"
default_decorator = ["YellowFgBright"]

[[command]]
regex = "(?<=(canonical\\s+name\\s+=\\s+)).*(?=\\.)"
default_decorator = ["MagentaFgBright"]

[[command]]
regex = "(?<=(Name:\\s+))\\S+"
default_decorator = ["BlueFgBright"]

[[command]]
regex = "^(\\S+\\.){1,}\\S+"
default_decorator = ["RedFgBright"]

[[command]]
regex = "\\*\\*(\\s+\\S+){1,}"
default_decorator = ["WhiteFgBright", "RedBgBright"]
