[[command]]
regex = "((?<=(PING\\s))|(?<=(^-{3}\\s)))\\S+"
default_decorator = ["MagentaFgBright"]

[[command]]
regex = "(?<=([\\d+\\sbytes]?\\s[fF]rom\\s)).+?(?=[:|\\s])"
default_decorator = ["CyanFgBright"]
optional_decorators = [["\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}", ["GreenFgBright"]]]

[[command]]
regex = "(?<=\\s(\\()).*?(?=(\\)))"
default_decorator = ["GreenFgBright"]

[[command]]
regex = "(?<=(icmp_seq=))[0-9]+"
default_decorator = ["YellowFgBright"]

[[command]]
regex = "(?<=(ttl=))[0-9]+"
default_decorator = ["YellowFgBright"]

[[command]]
regex = "(?<=(time=))[0-9]+.[0-9]+"
default_decorator = ["YellowFgBright"]

[[command]]
regex = "Destination Host Unreachable"
default_decorator = ["RedBgBright"]

[[command]]
regex = "min"
default_decorator = ["BlueFgBright"]

[[command]]
regex = "avg"
default_decorator = ["MagentaFgBright"]

[[command]]
regex = "max"
default_decorator = ["GreenFgBright"]

[[command]]
regex = "mdev|stddev"
default_decorator = ["BlackFgBright"]

[[command]]
regex = "(?<=(=\\s))[0-9]+.[0-9]+"
default_decorator = ["BlueFgBright"]

[[command]]
regex = "(?<=(=\\s[0-9]+.[0-9]+)\\/)[0-9]+.[0-9]+"
default_decorator = ["MagentaFgBright"]

[[command]]
regex = "(?<=(=\\s[0-9]+.[0-9]+)\\/[0-9]+.[0-9]+\\/)[0-9]+.[0-9]+"
default_decorator = ["GreenFgBright"]

[[command]]
regex = "(?<=(=\\s[0-9]+.[0-9]+)\\/[0-9]+.[0-9]+\\/[0-9]+.[0-9]+\\/)[0-9]+.[0-9]+"
default_decorator = ["BlackFgBright"]

[[command]]
regex = "\\S*\\%"
default_decorator = ["GreenFgBright"]
optional_decorators = [["0%", ["GreenFgBright"]], ["\\d{1,2}(\\.\\d+)?%", ["YellowFgBright"]], ["100%", ["RedBgBright"]]]
