[package]
name = "colorer"
version = "1.0.0-beta1"
authors = ["droppo"]
edition = "2021"
description = "Simple command line utility that add color to commands that do not have it by default."
documentation = "https://github.com/droppo/colorer"
repository = "https://github.com/droppo/colorer"
homepage = "https://github.com/droppo/colorer"
readme = "README.md"
license = "MIT"
keywords = ["cli", "parser", "terminal", "utility", "command"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "clrr"
path = "src/main.rs"


[dependencies]
ctrlc = "3.1.9"
nix = "0.22.0"
onig = "6.2.0"
pico-args = "0.4.2"
serde = "1.0.133"
serde_derive = "1.0.133"
serde_json = "1.0.74"
toml = "0.5.8"
